### ISSUE TITLE
Could you stop sending an e-mail to me?

### ISSUE THREAD

**Issue by nzw0301** [chalice-dev/awesome-chalice#5]
As in the title, could you stop sending an e-mail to me about this repo?

**Comment by yeukfei02** [comment]
@nzw0301 you can `unwatch` in your top right hand corner

**Comment by nzw0301** [comment]
I have never ever watched this repo. I mean that I have received some e-mail that introduces this repo.

**Comment by nzw0301** [comment]
FYI; The e-mail title was something like `AWS + python`. There was a link to this repo via `yesware.com` and some description of this repo.

**Comment by brianmingus2** [comment]
Your e-mail address is public on the web FYI. I was also once a PhD student in Machine Learning. It would be difficult to mark such an on-topic e-mail as spam, seeing as I got your e-mail from the list of people who had starred aws/chalice on GitHub :)

![image](https://user-images.githubusercontent.com/76971633/128555241-e97fb438-697d-4e77-b860-77b72f625328.png)
